package hatespeech.detection.model;

// Generated Nov 6, 2014 9:08:37 PM by Hibernate Tools 3.4.0.CR1

/**
 * Hashtag generated by hbm2java
 */
public class Hashtag implements java.io.Serializable {

	private static final long serialVersionUID = -7584178589930877737L;
	private Integer hashtagid;
	private String tag;
	private Tweet tweet;

	public Hashtag() {
	}

	public Hashtag(String tag) {
		this.tag = tag;
	}

	public Hashtag(String tag, Tweet tweet) {
		this.tag = tag;
		this.tweet = tweet;
	}

	public Integer getHashtagid() {
		return this.hashtagid;
	}

	public void setHashtagid(Integer hashtagid) {
		this.hashtagid = hashtagid;
	}

	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	public Tweet getTweet() {
		return this.tweet;
	}

	public void setTweets(Tweet tweet) {
		this.tweet = tweet;
	}

}
