package hatespeech.detection.model;

// Generated Nov 6, 2014 9:08:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private static final long serialVersionUID = -4985123072619540028L;
	private long userid;
	private String username;
	private String name;
	private Date lastupdate;
	private int friendscount;
	private int followerscount;
	private int listedcount;
	private int favoritecount;
	private int tweetcount;
	private int retweetcount;
	private Set<Tweet> retweets = new HashSet<Tweet>(0);
	private Set<User> usersForFollowerUserid = new HashSet<User>(0);
	private Set<User> usersForFollowedUserid = new HashSet<User>(0);
	private Set<Tweet> tweets = new HashSet<Tweet>(0);
	private Set<Tweet> tweets_Mentioned = new HashSet<Tweet>(0);
	private Set<User> usersForBlockedUserid = new HashSet<User>(0);
	private Set<Tweet> tweets_Favorites = new HashSet<Tweet>(0);
	private Set<User> usersForBlockerUserid = new HashSet<User>(0); 
	

	public User() {
	}
	public User(long userid) {
		this.userid=userid;
	}
	public User(long userid, String username, String name, Date lastupdate,
			int friendscount, int followerscount, int listedcount,
			int favoritecount, int tweetcount) {
		this.userid = userid;
		this.username = username;
		this.name = name;
		this.lastupdate = lastupdate;
		this.friendscount = friendscount;
		this.followerscount = followerscount;
		this.listedcount = listedcount;
		this.favoritecount = favoritecount;
		this.tweetcount = tweetcount;
	}


	public long getUserid() {
		return this.userid;
	}

	public void setUserid(long userid) {
		this.userid = userid;
	}

	public int getTweetcount() {
		return tweetcount;
	}

	public void setTweetcount(int tweetcount) {
		this.tweetcount = tweetcount;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getLastupdate() {
		return this.lastupdate;
	}

	public void setLastupdate(Date lastupdate) {
		this.lastupdate = lastupdate;
	}

	public int getFriendscount() {
		return this.friendscount;
	}

	public void setFriendscount(int friendscount) {
		this.friendscount = friendscount;
	}

	public int getFollowerscount() {
		return this.followerscount;
	}

	public void setFollowerscount(int followerscount) {
		this.followerscount = followerscount;
	}

	public int getListedcount() {
		return this.listedcount;
	}

	public void setListedcount(int listedcount) {
		this.listedcount = listedcount;
	}

	public int getFavoritecount() {
		return this.favoritecount;
	}

	public void setFavoritecount(int favoritecount) {
		this.favoritecount = favoritecount;
	}

	public int getRetweetcount() {
		return retweetcount;
	}

	public void setRetweetcount(int retweetcount) {
		this.retweetcount = retweetcount;
	}

	public Set<Tweet> getRetweets() {
		return retweets;
	}

	public void setRetweets(Set<Tweet> retweets) {
		this.retweets = retweets;
	}

	public Set<User> getUsersForFollowerUserid() {
		return usersForFollowerUserid;
	}

	public void setUsersForFollowerUserid(Set<User> usersForFollowerUserid) {
		this.usersForFollowerUserid = usersForFollowerUserid;
	}

	public Set<User> getUsersForFollowedUserid() {
		return usersForFollowedUserid;
	}

	public void setUsersForFollowedUserid(Set<User> usersForFollowedUserid) {
		this.usersForFollowedUserid = usersForFollowedUserid;
	}

	public Set<Tweet> getTweets() {
		return tweets;
	}

	public void setTweets(Set<Tweet> tweets) {
		this.tweets = tweets;
	}

	public Set<Tweet> getTweets_Mentioned() {
		return tweets_Mentioned;
	}

	public void setTweets_Mentioned(Set<Tweet> tweets_Mentioned) {
		this.tweets_Mentioned = tweets_Mentioned;
	}

	public Set<User> getUsersForBlockedUserid() {
		return usersForBlockedUserid;
	}

	public void setUsersForBlockedUserid(Set<User> usersForBlockedUserid) {
		this.usersForBlockedUserid = usersForBlockedUserid;
	}

	public Set<Tweet> getTweets_Favorites() {
		return tweets_Favorites;
	}

	public void setTweets_Favorites(Set<Tweet> tweets_Favorites) {
		this.tweets_Favorites = tweets_Favorites;
	}

	public Set<User> getUsersForBlockerUserid() {
		return usersForBlockerUserid;
	}

	public void setUsersForBlockerUserid(Set<User> usersForBlockerUserid) {
		this.usersForBlockerUserid = usersForBlockerUserid;
	}

	
}
